name: Code Quality Check and Merge

on:
  pull_request:
    branches: [main, saqib,taimoor]
    types: [closed]
  push:
    branches: [main, saqib,taimoor]
jobs:
  build:
    if: github.event.pull_request.merged == true || github.event.push==true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        make install
    - name: Setting files
      uses: peter-evans/create-pull-request@v4
  
    - name: Test
      if: steps.changed-files-excluded.outputs.any_changed == 'true'
      run: |
        make test
