name: Code Quality Check and Merge

on:
  push:
    branches:
      - taimoor
      - saqib
  pull_request:
    branches:
      - taimoor
      - saqib

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: 'Code quality check passed'
        commit-message: 'Merge feature branches into main'
        branch: 'main'
        body: |
          Code quality check passed for feature branches:
          - taimoor
          - saqib
